import Image from "next/image";
import DiagnosticNavigator from "./DiagnosticNavigator";

const situationColumns = [
  { label: "Когда не сходятся продажи", items: ["Нас не видят", "Нас видят, но не заказывают", "Нас сравнивают только по цене", "Заказывают, но повторно не заказывают"] },
  { label: "Когда непонятно, что чинить", items: ["Маркетолог есть, но непонятно, что он реально даёт", "Меняли сайт, рекламу или подрядчиков, а яснее не стало", "Продукт хороший, но рынок как будто этого не понимает"] },
  { label: "Когда нужен внешний взгляд", items: ["Хотим выйти на новый рынок, но не хотим строить решение на догадках", "Нужно понять, что делать, а внедрять будем сами", "Есть задача, но мы сами уже слишком близко к бизнесу, чтобы увидеть причину"] },
] as const;

const process = [
  ["01", "Вы рассказываете, что происходит", "Двух-трёх предложений достаточно. Не нужно заранее понимать причину или выбирать услугу."],
  ["02", "Мы разговариваем 20–30 минут", "Я уточняю, что уже пробовали, какие есть цифры и что сейчас больше всего беспокоит."],
  ["03", "Я говорю, что вижу", "Отделяем то, что уже известно, от предположений и определяем, что разумно проверить или сделать первым."],
] as const;

const routes = [
  ["01", "Сделать самим", "Если стало понятно, что делать, вы получаете логику действий и можете внедрять решение самостоятельно."],
  ["02", "Передать исполнителю", "Если нужен конкретный специалист или агентство, становится понятно, что именно им поручить и как проверить работу."],
  ["03", "Продолжить разбор со мной", "Если причина пока не ясна или решение требует отдельной проверки, можно перейти к платной работе по конкретной задаче."],
] as const;

export default function Home() {
  return <main id="top">
    <div className="page-shell">
      <header className="site-nav"><a className="site-brand" href="#top">Владимир Шашков</a><nav aria-label="Основная навигация"><a href="#situations">С чем приходят</a><a href="#diagnostic">Мини-разбор</a><a href="#proof">Пример</a><a href="#work">Работа</a><a className="nav-cta" href="#contact">Написать</a></nav></header>
      <section className="hero"><div className="hero-copy"><p className="eyebrow">Для собственников действующего бизнеса</p><h1>Не уверены, что именно сейчас нужно менять в бизнесе?</h1><p className="hero-lead">Продажи не растут, клиенты выбирают других, а внутри звучат разные версии: нужно больше рекламы, новый сайт, другой маркетолог, изменить продукт или продажи. Ошибка здесь стоит денег — можно снова вложиться в решение, которое не устраняет причину.</p><p className="hero-principle">Сначала разобраться, что происходит. Потом решить, что делать — и на что пока не тратить деньги.</p><div className="hero-actions"><a className="button" href="#situations">Узнать свою ситуацию</a><a className="text-link" href="https://t.me/ShashkovVlad" target="_blank" rel="noreferrer">Написать в Telegram</a></div><div className="hero-trust" aria-label="Опыт Владимира Шашкова"><span><strong>20+ лет</strong> в бизнесе и управлении</span><span><strong>Executive MBA</strong></span><span><strong>Инженерия → развитие → маркетинг</strong></span></div></div><figure className="hero-photo"><Image src="/vladimir-photo.jpg" alt="Владимир Шашков" width={1206} height={1210} priority /></figure></section>
    </div>

    <section className="situations-stage" id="situations"><div className="page-shell"><div className="section-intro situations-intro"><p className="eyebrow">Возможно, это про вас</p><h2>С какой проблемой вы сейчас живёте?</h2><p>Не нужно знать маркетинговый термин или заранее понимать причину. Достаточно узнать свою ситуацию.</p></div>
      <article className="lead-situation"><p className="lead-label">Реальный запрос собственника</p><blockquote>«У меня нет бюджета на маркетинг, но я хочу, чтобы пришёл человек, сказал, что делать, а я сама сделаю»</blockquote><p className="lead-answer">Да, так тоже можно. Не обязательно нанимать маркетолога или агентство. Иногда нужен внешний разбор: понять приоритеты, а внедрять решение своими силами.</p></article>
      <div className="situation-columns">{situationColumns.map((group,index)=><article className="situation-column" key={group.label}><span className="column-index">0{index+1}</span><h3>{group.label}</h3><div className="situation-list">{group.items.map(item=><p key={item}>«{item}»</p>)}</div></article>)}</div><DiagnosticNavigator /></div>
      <div className="capture-band"><div className="page-shell capture-grid"><div className="capture-copy"><p className="eyebrow eyebrow-light">Если узнали свою ситуацию</p><h2>Можно просто написать, что происходит</h2><p>Двух-трёх предложений достаточно. Не нужно готовить бриф, выбирать услугу или правильно называть причину.</p></div><form className="quick-form" method="post" action="/api/contact"><input type="hidden" name="source" value="early-form" /><label>Что происходит?<textarea name="situation" required placeholder="Например: нас видят, но почти не заказывают" /></label><label>Как с вами связаться?<input name="contact" required placeholder="Email или Telegram" /></label><button className="button button-light" type="submit">Описать ситуацию</button><p className="form-promise">Если вижу, что могу быть полезен, предложу короткий разговор на 20–30 минут. Бесплатно и без обязательства продолжать. Обычно отвечаю в течение рабочего дня.</p></form></div></div>
    </section>

    <section className="process-stage" id="process"><div className="page-shell"><div className="section-intro process-intro"><p className="eyebrow">Что будет после сообщения</p><h2>Вы должны быстро понять, понял ли я вашу проблему</h2><p>Первый разговор нужен не для продажи большого проекта. Сначала я должен разобраться в вашей ситуации и показать, куда, по моему мнению, стоит смотреть.</p></div><div className="process-line">{process.map(([number,title,text])=><article className="process-item" key={number}><span className="process-number">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="process-outcome"><p className="eyebrow">Что вы получаете</p><p className="outcome-statement">Ясность, что делать первым — и на что пока не тратить деньги.</p><div className="owner-result-list"><p><strong>Не переделывать всё подряд</strong><span>пока не понятно, где на самом деле проблема.</span></p><p><strong>Понимать, что требовать от маркетолога или подрядчика</strong><span>и как оценить, помогает ли его работа бизнесу.</span></p><p><strong>Отделить факты от догадок</strong><span>и проверить самое важное до больших затрат.</span></p><p><strong>Выбрать следующий шаг</strong><span>сделать самим, передать исполнителю или продолжить разбор.</span></p></div></div><div className="routes-block"><div className="section-intro routes-intro"><p className="eyebrow">Что бывает дальше</p><h2>Не обязательно продолжать работу со мной</h2><p>Если после разговора стало понятно, что делать, этого может быть достаточно.</p></div><div className="routes-grid">{routes.map(([number,title,text])=><article className="route-card" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></div></section>

    <section className="proof-stage" id="proof"><div className="page-shell"><div className="section-intro proof-intro"><p className="eyebrow">Один реальный пример</p><h2>Как первоначальная версия проблемы меняется после проверки фактами</h2><p>SLED Systems — не доказательство того, что одна схема решает все ситуации выше. Это пример самого способа работы: исходный запрос проверяется данными, и решение меняется, если факты ведут в другую сторону.</p></div><article className="case-editorial"><div className="case-side"><p className="case-label">SLED Systems</p><span className="case-type">Проект в работе</span></div><div className="case-main"><div className="case-shift"><div><span>С чего начали</span><h3>Получать больше квалифицированных запросов за пределами домашнего региона</h3><p>На поверхности это выглядело как задача сайта, SEO, рекламы или лидогенерации.</p></div><div><span>Что показали данные</span><h3>Проблему нельзя было свести к «нужно больше трафика»</h3><p>В отгрузках за 2025 год сайт дал 1,16% выручки, активная выездная отработка — 30,18%, повторные заказы — 52,49%. Эти данные не доказывают проблему узнаваемости сами по себе. Они показали другое: исходную гипотезу «нужно просто больше входящих» нельзя было принимать без дальнейшей проверки.</p></div></div><div className="owner-result-list" style={{marginTop:42}}><p><strong>Обнаружили</strong><span>поздний вход в проект, дефицит доказательств надёжного выбора и зависимость продаж от личной инженерной проработки собственника.</span></p><p><strong>Изменили постановку задачи</strong><span>не «как купить больше входящих», а «как раньше попадать в проект, становиться безопасным вариантом и масштабировать доверие».</span></p><p><strong>Следующий выбор</strong><span>проверять ранний доступ к проектам, доказательную систему и экономику маршрутов, а не автоматически наращивать рекламу.</span></p><p><strong>Статус результата</strong><span>проект находится на этапе проверки стратегического выбора. Финансовый эффект пока не заявляю — он ещё не подтверждён внедрением.</span></p></div><p className="research-thesis">Для меня это и есть смысл диагностики: не красиво объяснить исходный запрос, а изменить решение, если факты показывают другую проблему.</p></div></article></div></section>

    <section className="work-stage" id="work"><div className="page-shell"><div className="section-intro"><p className="eyebrow">Не один тип бизнеса</p><h2>Та же логика работает и там, где клиент — обычный человек</h2><p>Например, в исследовании фитнес-бизнеса вопрос раскладывался как рынок → выбор клиента → предложение → цена → привлечение → использование → удержание → экономика.</p></div><div className="work-grid"><article className="work-card"><p className="work-label">Исследование</p><h3>6 503 вакансии HeadHunter</h3><p>Не «что сейчас модно», а что реально требуют работодатели от маркетинга и где проходят границы ролей.</p></article><article className="work-card"><p className="work-label">B2C / фитнес</p><h3>От рынка до экономики</h3><p>Пример того, что диагностическая логика не ограничивается сложным B2B.</p><a className="text-link" href="/fitness-report.pdf" target="_blank" rel="noreferrer">Открыть PDF →</a></article><article className="work-card"><p className="work-label">Рабочая система</p><h3>Источники + данные + ИИ</h3><p>ИИ работает не вместо источников: я использую собственную базу из исследований, академических и практических материалов, а выводы отделяю от гипотез.</p></article></div></div></section>

    <section className="about-stage"><div className="page-shell about-grid"><div><p className="eyebrow">Почему я так работаю</p><h2>Инженерный способ думать о маркетинге</h2></div><div className="about-copy"><p>Математическое и инженерное образование научило меня не принимать первое объяснение за причину. Более 20 лет в управлении и развитии бизнеса — смотреть на решение через результат компании, а не отдельной функции.</p><p>Executive MBA добавил язык стратегии и экономики. Маркетинг для меня — способ связать рынок, клиента, предложение, продажи и деньги в одну проверяемую систему.</p><p className="about-accent">ИИ здесь не «магия». Это рабочий слой поверх собственной базы знаний и реальных данных, который помогает быстрее сравнивать версии и находить противоречия.</p></div></div></section>

    <section className="faq-stage"><div className="page-shell"><div className="section-intro"><p className="eyebrow">Практические вопросы</p><h2>До первого сообщения</h2></div><div className="faq-list"><details><summary>Сколько стоит первый разговор?</summary><p>Ничего. Первый разговор занимает около 20–30 минут и нужен, чтобы понять задачу и решить, есть ли смысл идти дальше.</p></details><details><summary>Обязательно ли продолжать работу после разговора?</summary><p>Нет. Иногда достаточно понять, что делать дальше своими силами. Иногда нужен конкретный исполнитель, а иногда есть смысл продолжить разбор со мной.</p></details><details><summary>Что если проблема окажется вообще не в маркетинге?</summary><p>Это нормальный результат. Лучше понять это до того, как вкладываться в новый сайт, рекламу или смену подрядчика.</p></details><details><summary>Что нужно подготовить?</summary><p>Для первого сообщения — ничего. Если для разговора понадобятся цифры, материалы или примеры сделок, я скажу, что именно стоит посмотреть.</p></details><details><summary>Сколько стоит полноценный разбор?</summary><p>Зависит от вопроса и объёма проверки. Сначала нужно понять, какая работа действительно нужна; после этого можно определить формат и стоимость.</p></details><details><summary>Когда вы ответите?</summary><p>Обычно в течение рабочего дня.</p></details></div></div></section>

    <section className="contact-stage" id="contact"><div className="page-shell contact-grid"><div className="contact-copy"><p className="eyebrow eyebrow-light">Если есть задача, но решение пока не очевидно</p><h2>Расскажите, что происходит</h2><p>Не нужно готовить бриф. Напишите своими словами. Первый разговор — 20–30 минут, бесплатно и без обязательства продолжать.</p><div className="contact-links"><a href="https://t.me/ShashkovVlad" target="_blank" rel="noreferrer">Telegram · @ShashkovVlad</a><a href="mailto:shashkov.systemservice@gmail.com">shashkov.systemservice@gmail.com</a></div></div><form className="contact-form" method="post" action="/api/contact"><input type="hidden" name="source" value="final-form" /><label>Что происходит?<textarea name="situation" required placeholder="Двух-трёх предложений достаточно" /></label><label>Как с вами связаться?<input name="contact" required placeholder="Email или Telegram" /></label><button className="button button-light" type="submit">Отправить</button><p className="form-promise">Обычно отвечаю в течение рабочего дня. Если вижу, что сначала нужен не мой формат работы, скажу об этом прямо.</p></form></div></section>
    <a className="sticky-contact" href="#contact">Описать ситуацию</a>
  </main>;
}