"use client";

import {useEffect,useMemo,useState} from "react";
import {entities,groups,links,levelLabel,type EntityKey,type Level,type LinkKey} from "./check-data";

const emptyEntities=Object.fromEntries(entities.map(x=>[x.key,0])) as Record<EntityKey,Level>;
const emptyLinks=Object.fromEntries(links.map(x=>[x.key,0])) as Record<LinkKey,Level>;

export default function MarketingCheckClient(){
 const [started,setStarted]=useState(false);
 const [step,setStep]=useState(0);
 const [entityState,setEntityState]=useState<Record<EntityKey,Level>>(emptyEntities);
 const [linkState,setLinkState]=useState<Record<LinkKey,Level>>(emptyLinks);
 const [name,setName]=useState("");
 const [company,setCompany]=useState("");
 const [note,setNote]=useState("");
 const [copied,setCopied]=useState(false);

 useEffect(()=>{try{const raw=localStorage.getItem("vsh-marketing-check-v1");if(!raw)return;const s=JSON.parse(raw);if(s.entityState)setEntityState(s.entityState);if(s.linkState)setLinkState(s.linkState);if(s.name)setName(s.name);if(s.company)setCompany(s.company);if(s.note)setNote(s.note);}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("vsh-marketing-check-v1",JSON.stringify({entityState,linkState,name,company,note}));}catch{}},[entityState,linkState,name,company,note]);

 const scores=useMemo(()=>{const ev=Object.values(entityState),lv=Object.values(linkState);const coverage=Math.round(ev.filter(x=>x>0).length/ev.length*100);const clarity=Math.round(ev.reduce((a,b)=>a+b,0)/(ev.length*2)*100);const coherence=Math.round(lv.reduce((a,b)=>a+b,0)/(lv.length*2)*100);const proof=Math.round((entityState.proof+linkState.promise_proof)/4*100);const total=Math.round(clarity*.35+coherence*.35+proof*.2+coverage*.1);return{coverage,clarity,coherence,proof,total};},[entityState,linkState]);
 const gaps=useMemo(()=>entities.filter(x=>entityState[x.key]<2).sort((a,b)=>entityState[a.key]-entityState[b.key]).slice(0,5),[entityState]);
 const weakLinks=useMemo(()=>links.filter(x=>linkState[x.key]<2),[linkState]);
 const firstAction=useMemo(()=>{const missing=entities.find(x=>entityState[x.key]===0);if(missing)return`Сначала зафиксируйте «${missing.title}». Пока эта сущность отсутствует, нижние уровни будут строиться на предположениях.`;const weak=links.find(x=>linkState[x.key]<2);if(weak)return`Первым делом проверьте связь «${weak.title}». Здесь сейчас главный риск логического разрыва.`;if(entityState.proof<2)return"Привяжите ключевые обещания к конкретным кейсам, цифрам и фактам.";return"Базовая логика собрана. Следующий шаг — проверить её на рынке: интервью, Win/Loss, спрос, конкуренты и реальные сделки.";},[entityState,linkState]);
 const report=useMemo(()=>[
  "ПРОВЕРКА МАРКЕТИНГОВОЙ ЛОГИКИ",name&&`Имя: ${name}`,company&&`Компания: ${company}`,"",
  `Общий индекс: ${scores.total}%`,`Наличие сущностей: ${scores.coverage}%`,`Ясность: ${scores.clarity}%`,`Связность: ${scores.coherence}%`,`Доказанность: ${scores.proof}%`,"",
  "СУЩНОСТИ",...entities.map(x=>`${x.title}: ${levelLabel(entityState[x.key])}`),"","СВЯЗИ",...links.map(x=>`${x.title}: ${levelLabel(linkState[x.key])}`),"",`ПЕРВЫЙ ШАГ: ${firstAction}`,note&&`Комментарий: ${note}`
 ].filter(Boolean).join("\n"),[name,company,scores,entityState,linkState,firstAction,note]);

 async function copy(){try{await navigator.clipboard.writeText(report);setCopied(true);setTimeout(()=>setCopied(false),1500);}catch{}}
 async function send(){try{await navigator.clipboard.writeText(report);}catch{}window.open("https://t.me/ShashkovVlad","_blank","noopener,noreferrer");}
 function reset(){setEntityState(emptyEntities);setLinkState(emptyLinks);setName("");setCompany("");setNote("");setStep(0);try{localStorage.removeItem("vsh-marketing-check-v1");}catch{}}

 if(!started)return <main className="mc-shell"><header className="mc-nav"><a href="/art-direction-2027-lab" className="mc-brand"><b>ВШ</b><span>Владимир Шашков</span></a><span>Бесплатный инструмент</span></header><section className="mc-intro"><div className="mc-kicker">Проверка маркетинговой логики · 7–10 минут</div><h1>Проверьте, собрана ли у бизнеса <em>логика выбора клиента.</em></h1><p className="mc-lead">Не тест на знания. Проверяем наличие ключевых маркетинговых сущностей, качество формулировок и связи между ними — от смысла бизнеса до оффера и доказательств.</p><div className="mc-preview-grid"><article><strong>15</strong><span>ключевых сущностей</span></article><article><strong>6</strong><span>критических связей</span></article><article><strong>1</strong><span>первый шаг по итогам</span></article></div><button className="mc-primary" onClick={()=>setStarted(true)}>Начать проверку →</button><p className="mc-muted">Результат остаётся у вас. В конце его можно сохранить, скопировать или отправить Владимиру.</p></section></main>;

 const onEntity=step<groups.length,onLinks=step===groups.length,onResult=step===groups.length+1;
 const group=groups[Math.min(step,groups.length-1)];
 return <main className="mc-shell"><header className="mc-nav"><a href="/art-direction-2027-lab" className="mc-brand"><b>ВШ</b><span>Владимир Шашков</span></a><span>{onResult?"Результат":`Шаг ${step+1} из ${groups.length+1}`}</span></header><div className="mc-progress"><i style={{width:`${onResult?100:Math.round(step/(groups.length+1)*100)}%`}}/></div>
 {onEntity&&<section className="mc-stage"><div className="mc-stage-head"><span>{group.kicker}</span><h1>{group.title}</h1><p>Оцените текущее состояние, а не то, что «примерно есть в голове».</p></div><div className="mc-questions">{group.keys.map(key=>{const item=entities.find(x=>x.key===key)!;return <article className="mc-question" key={key}><div><small>{item.title}</small><h2>{item.question}</h2><p>{item.help}</p></div><div className="mc-choice-row">{([0,1,2] as Level[]).map(v=><button key={v} className={entityState[key]===v?"is-active":""} onClick={()=>setEntityState(s=>({...s,[key]:v}))}>{levelLabel(v)}</button>)}</div></article>})}</div><div className="mc-actions"><button className="mc-secondary" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}>← Назад</button><button className="mc-primary" onClick={()=>setStep(s=>s+1)}>Дальше →</button></div></section>}
 {onLinks&&<section className="mc-stage"><div className="mc-stage-head"><span>08 · Связность</span><h1>Проверяем не поля, а связи.</h1><p>Заполненная система всё равно может разваливаться, если нижние уровни не вытекают из верхних.</p></div><div className="mc-questions">{links.map(item=><article className="mc-question" key={item.key}><div><small>{item.title}</small><h2>{item.question}</h2></div><div className="mc-choice-row">{([0,1,2] as Level[]).map(v=><button key={v} className={linkState[item.key]===v?"is-active":""} onClick={()=>setLinkState(s=>({...s,[item.key]:v}))}>{v===2?"Да":v===1?"Частично":"Нет / не уверен"}</button>)}</div></article>)}</div><div className="mc-actions"><button className="mc-secondary" onClick={()=>setStep(s=>s-1)}>← Назад</button><button className="mc-primary" onClick={()=>setStep(s=>s+1)}>Показать результат →</button></div></section>}
 {onResult&&<section className="mc-result"><div className="mc-result-hero"><span>Ваша карта маркетинговой логики</span><div className="mc-score"><strong>{scores.total}</strong><small>/100</small></div><h1>{scores.total>=80?"Система в целом собрана.":scores.total>=55?"Основа есть, но есть логические разрывы.":"Система пока собрана фрагментами."}</h1><p>{firstAction}</p></div><div className="mc-metrics"><article><strong>{scores.coverage}%</strong><span>Наличие сущностей</span></article><article><strong>{scores.clarity}%</strong><span>Ясность</span></article><article><strong>{scores.coherence}%</strong><span>Связность</span></article><article><strong>{scores.proof}%</strong><span>Доказанность</span></article></div><div className="mc-result-grid"><article className="mc-panel"><span>Где есть риск</span><h2>Сущности, которые стоит укрепить</h2><ul>{gaps.map(x=><li key={x.key}><b>{x.title}</b><em>{levelLabel(entityState[x.key])}</em></li>)}</ul></article><article className="mc-panel"><span>Связность</span><h2>Где может рваться логика</h2><ul>{weakLinks.map(x=><li key={x.key}><b>{x.title}</b><em>{linkState[x.key]===1?"Частично":"Не подтверждено"}</em></li>)}</ul></article></div><article className="mc-next"><span>Что делать первым</span><h2>{firstAction}</h2><p>Не переписывайте сразу сайт, рекламу или презентацию. Сначала исправьте верхний логический разрыв.</p></article><div className="mc-personalize"><h2>Сохраните результат с контекстом</h2><div className="mc-fields"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Имя"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Компания / проект"/></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Что сейчас больше всего беспокоит в маркетинге или росте? (необязательно)"/></div><div className="mc-result-actions"><button className="mc-secondary" onClick={()=>window.print()}>Сохранить себе / PDF</button><button className="mc-secondary" onClick={copy}>{copied?"Скопировано":"Скопировать результат"}</button><button className="mc-primary" onClick={send}>Отправить Владимиру →</button></div><p className="mc-send-note">При отправке результат копируется, затем открывается личный Telegram Владимира. Вставьте текст в сообщение — он увидит всю карту.</p><button className="mc-reset" onClick={reset}>Пройти заново</button></section>}
 </main>;
}
