export type MarketingPdfPayload = {
  total:number; coverage:number; clarity:number; coherence:number; proof:number;
  resultLabel:string; resultText:string; firstAction:string;
  groups:Array<{title:string;value:number}>;
  gaps:Array<{title:string;status:string}>;
  weakLinks:Array<{title:string;status:string}>;
  name?:string; company?:string; note?:string;
};

type PdfPageImage={bytes:Uint8Array;width:number;height:number};
const PAGE_W=1240,PAGE_H=1754,PDF_W=595.28,PDF_H=841.89,ORANGE="#ff6500";

function wrapLines(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const out:string[]=[];for(const paragraph of String(text||"").split(/\n+/)){const words=paragraph.trim().split(/\s+/).filter(Boolean);if(!words.length){out.push("");continue}let line=words[0];for(const word of words.slice(1)){const test=`${line} ${word}`;if(ctx.measureText(test).width<=maxWidth)line=test;else{out.push(line);line=word}}out.push(line)}return out}
function jpegBytes(dataUrl:string){const base64=dataUrl.split(",")[1]||"",binary=atob(base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}
function concatBytes(parts:Uint8Array[]){const total=parts.reduce((s,p)=>s+p.length,0),out=new Uint8Array(total);let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length}return out}
function buildPdf(pages:PdfPageImage[]){const enc=new TextEncoder(),parts:Uint8Array[]=[],offsets:number[]=[0];let length=0;const push=(part:string|Uint8Array)=>{const b=typeof part==="string"?enc.encode(part):part;parts.push(b);length+=b.length};const obj=(id:number,body:string)=>{offsets[id]=length;push(`${id} 0 obj\n${body}\nendobj\n`)};push("%PDF-1.4\n%MarketingDiagnostic\n");const kids=pages.map((_,i)=>`${3+i*3} 0 R`).join(" ");obj(1,"<< /Type /Catalog /Pages 2 0 R >>");obj(2,`<< /Type /Pages /Count ${pages.length} /Kids [${kids}] >>`);pages.forEach((page,i)=>{const pageId=3+i*3,imageId=pageId+1,contentId=pageId+2,stream=`q\n${PDF_W} 0 0 ${PDF_H} 0 0 cm\n/Im0 Do\nQ\n`;obj(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PDF_W} ${PDF_H}] /Resources << /XObject << /Im0 ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`);offsets[imageId]=length;push(`${imageId} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${page.width} /Height ${page.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${page.bytes.length} >>\nstream\n`);push(page.bytes);push("\nendstream\nendobj\n");obj(contentId,`<< /Length ${enc.encode(stream).length} >>\nstream\n${stream}endstream`)});const xref=length,count=2+pages.length*3;push(`xref\n0 ${count+1}\n0000000000 65535 f \n`);for(let id=1;id<=count;id++)push(`${String(offsets[id]||0).padStart(10,"0")} 00000 n \n`);push(`trailer\n<< /Size ${count+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);return new Blob([concatBytes(parts)],{type:"application/pdf"})}

export async function renderMarketingDiagnosticPdf(p:MarketingPdfPayload){await document.fonts?.ready;const pages:PdfPageImage[]=[];let canvas=document.createElement("canvas"),ctx=canvas.getContext("2d")!;canvas.width=PAGE_W;canvas.height=PAGE_H;const makePage=(pageNo:number)=>{canvas=document.createElement("canvas");canvas.width=PAGE_W;canvas.height=PAGE_H;ctx=canvas.getContext("2d",{alpha:false})!;ctx.fillStyle="#fbfaf7";ctx.fillRect(0,0,PAGE_W,PAGE_H);ctx.fillStyle="#17191d";ctx.fillRect(0,0,PAGE_W,150);ctx.fillStyle="#fff";ctx.font="700 30px Arial, sans-serif";ctx.fillText("ВШ   Владимир Шашков",90,66);ctx.fillStyle="#d8d8d8";ctx.font="400 19px Arial, sans-serif";ctx.fillText("Экспресс-диагностика маркетинговой логики",90,105);ctx.textAlign="right";ctx.fillText(`стр. ${pageNo}`,PAGE_W-90,82);ctx.textAlign="left"};const save=()=>pages.push({bytes:jpegBytes(canvas.toDataURL("image/jpeg",.92)),width:PAGE_W,height:PAGE_H});const drawWrapped=(text:string,x:number,y:number,max:number,font:string,color:string,lineHeight:number)=>{ctx.font=font;ctx.fillStyle=color;for(const line of wrapLines(ctx,text,max)){ctx.fillText(line,x,y);y+=lineHeight}return y};

 makePage(1);let y=240;ctx.fillStyle=ORANGE;ctx.font="700 19px Arial, sans-serif";ctx.fillText("ИНДЕКС МАРКЕТИНГОВОЙ ЛОГИКИ",90,y);y+=130;ctx.fillStyle="#17191d";ctx.font="800 132px Arial, sans-serif";ctx.fillText(`${p.total}%`,90,y);y+=62;ctx.font="700 34px Arial, sans-serif";ctx.fillText(p.resultLabel,90,y);y+=62;y=drawWrapped(p.resultText,90,y,1040,"400 28px Arial, sans-serif","#565e69",40)+38;
 ctx.fillStyle="#17191d";ctx.font="700 21px Arial, sans-serif";ctx.fillText("4 КЛЮЧЕВЫХ ПОКАЗАТЕЛЯ",90,y);y+=40;const metrics=[["Система собрана",p.coverage],["Формулировки ясны",p.clarity],["Логика связана",p.coherence],["Обещания доказаны",p.proof]] as const;metrics.forEach(([label,val],i)=>{const x=90+(i%2)*530,yy=y+Math.floor(i/2)*158;ctx.fillStyle="#fff";ctx.fillRect(x,yy,490,132);ctx.fillStyle="#17191d";ctx.font="800 48px Arial, sans-serif";ctx.fillText(`${val}%`,x+24,yy+58);ctx.font="700 20px Arial, sans-serif";ctx.fillText(label,x+24,yy+98)});y+=350;ctx.fillStyle="#17191d";ctx.font="700 21px Arial, sans-serif";ctx.fillText("АРХИТЕКТУРА СИСТЕМЫ",90,y);y+=44;p.groups.forEach((g,i)=>{ctx.fillStyle="#17191d";ctx.font="700 21px Arial, sans-serif";ctx.fillText(`${String(i+1).padStart(2,"0")}  ${g.title}`,90,y);ctx.textAlign="right";ctx.fillText(`${g.value}%`,PAGE_W-90,y);ctx.textAlign="left";ctx.fillStyle="#e2e1dc";ctx.fillRect(90,y+16,1060,10);ctx.fillStyle=ORANGE;ctx.fillRect(90,y+16,1060*g.value/100,10);y+=72});ctx.fillStyle="#777";ctx.font="400 17px Arial, sans-serif";ctx.fillText("vshashkov.ru",90,PAGE_H-50);save();

 makePage(2);y=230;ctx.fillStyle="#17191d";ctx.font="800 48px Arial, sans-serif";ctx.fillText("Где сейчас рвётся логика",90,y);y+=72;ctx.fillStyle=ORANGE;ctx.font="700 19px Arial, sans-serif";ctx.fillText("СУЩНОСТИ, КОТОРЫЕ НУЖНО УКРЕПИТЬ",90,y);y+=44;const gaps=p.gaps.length?p.gaps:[{title:"Критичных пробелов не найдено",status:"Сущности в целом собраны"}];gaps.forEach(g=>{ctx.fillStyle="#17191d";ctx.font="700 23px Arial, sans-serif";ctx.fillText(g.title,90,y);ctx.fillStyle="#707070";ctx.font="400 19px Arial, sans-serif";ctx.fillText(g.status,440,y);y+=54});y+=18;ctx.fillStyle=ORANGE;ctx.font="700 19px Arial, sans-serif";ctx.fillText("КРИТИЧЕСКИЕ СВЯЗИ",90,y);y+=44;const weak=p.weakLinks.length?p.weakLinks:[{title:"Критичных разрывов не найдено",status:"Проверенные связи согласованы"}];weak.forEach(g=>{ctx.fillStyle="#17191d";ctx.font="700 22px Arial, sans-serif";ctx.fillText(g.title,90,y);ctx.fillStyle="#707070";ctx.font="400 19px Arial, sans-serif";ctx.fillText(g.status,520,y);y+=52});y+=28;ctx.fillStyle=ORANGE;ctx.font="700 19px Arial, sans-serif";ctx.fillText("ПЕРВОЕ ДЕЙСТВИЕ",90,y);y+=48;y=drawWrapped(p.firstAction,90,y,1040,"700 31px Arial, sans-serif","#17191d",44)+38;if(p.name||p.company||p.note){ctx.fillStyle="#17191d";ctx.font="700 19px Arial, sans-serif";ctx.fillText("КОНТЕКСТ",90,y);y+=38;ctx.fillStyle="#666";ctx.font="400 19px Arial, sans-serif";if(p.name){ctx.fillText(`Имя: ${p.name}`,90,y);y+=30}if(p.company){ctx.fillText(`Компания / проект: ${p.company}`,90,y);y+=30}if(p.note)y=drawWrapped(`Комментарий: ${p.note}`,90,y,1040,"400 19px Arial, sans-serif","#666",30)}ctx.fillStyle="#777";ctx.font="400 17px Arial, sans-serif";ctx.fillText("Результат экспресс-диагностики · Владимир Шашков · vshashkov.ru",90,PAGE_H-50);save();
 return new File([buildPdf(pages)],`marketing-diagnostic-${new Date().toISOString().slice(0,10)}.pdf`,{type:"application/pdf"});
}
